apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-psu
  namespace: devops-psu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-psu
  template:
    metadata:
      labels:
        app: devops-psu
    spec:
      containers:
        - name: devops-psu-server
          image: agishevdm/devops-psu:latest
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: service-devops
  namespace: devops-psu
spec:
  type: LoadBalancer
  selector:
    app: devops-psu
  ports:
    - protocol: TCP
      port: 12345
      targetPort: 8000
  externalIPs:
    - 127.0.0.1
