name: CI Pipeline
on:
  push:
    branches: [dev]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - run: pip install -r requirements.txt
      - run: pylint -d C0114,C0115,C0116 server/application.py

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - run: pip install -r requirements.txt
      - run: pytest server/test_application.py -v

  build-test:
    needs: [lint, unit-tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker build -t test-image ./server --file ./server/dockerfile
      - run: docker run -d --name app-server8000 -p 8000:8000 test-image
      - run: sleep 10
      - run: 'curl 127.0.0.1:8000'
