name: CD Pipeline
on:
  push:
    branches: [master]

permissions:
  contents: write

jobs:
  push-to-dockerhub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: ./server
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/devops-psu:latest

  update-manifest:
    needs: [push-to-dockerhub]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update release date
        run: sed -i "s/release-date: .*/release-date: $(date +%s)/g" ./server-k8s-manifests/devops-psu.yml
      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add ./server-k8s-manifests/devops-psu.yml
          git commit -m "Update release date"
          git push
